from closedUnilaterallyLinkedList import ClosedUnidirectionalLinkedList as LinkedList
from subscriber import Subscriber

linked_list = LinkedList()
subs1 = Subscriber(380636834437, "Сопенко", "Євген", "Степонович", "Симоненка 9/7")
subs2 = Subscriber(3806368344389, "Максійчук", "Остап", "Іванович", "Петлюри 15/2")
subs3 = Subscriber(380636634437, "Урбан", "Данило", "Андрійович", "Липинського 16/45")
subs4 = Subscriber(380637634437, "Інак", "Петро", "Ігорович", "Марчука 384/4")
linked_list.add_subscriber(subs1)
linked_list.add_subscriber(subs2)
print("Printed list with three elements:\n")
linked_list.print_list()
print("Find the person with surname:\n")
linked_list.find_a_person_with_surname("Максійчук")
print("\nPrint the list:\n")
linked_list.print_list()
print("Get the element by key 0: \n")
print(linked_list.get(0), end='')
print("Get the information by key 0: \n")
linked_list.get_information_about_person(0)
print("Print the list:\n")
linked_list.print_list()
print("Add 2 element: \n")
linked_list.put_by_phone_number_sorted_list(subs3)
linked_list.put_by_phone_number_sorted_list(subs4)
print("Print the list:\n")
linked_list.print_list()
print("Delete an item: \n")
linked_list.delete_person_details_with_index(1)
print("Print the list:\n")
linked_list.print_list()
linked_list.delete()
